"""init

Revision ID: c5a9edd264f3
Revises: 
Create Date: 2019-08-22 17:00:00.686372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a9edd264f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('image', sa.String(length=280), nullable=False),
    sa.Column('intro', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('banner',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=280), nullable=False),
    sa.Column('link_url', sa.String(length=280), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('image', sa.String(length=280), nullable=False),
    sa.Column('intro', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('head_portrait', sa.String(length=280), nullable=True),
    sa.Column('intro', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Enum('1', '2', '3', '4', '5'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('beast',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head_portrait', sa.String(length=280), nullable=False),
    sa.Column('attribute', sa.Integer(), nullable=False),
    sa.Column('site', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(length=680), nullable=True),
    sa.Column('image_list', sa.String(length=1120), nullable=True),
    sa.ForeignKeyConstraint(['attribute'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['site'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('head_portrait', sa.String(length=280), nullable=False),
    sa.Column('gender', sa.Enum('0', '1'), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('attribute', sa.Integer(), nullable=False),
    sa.Column('site', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(length=680), nullable=True),
    sa.Column('image_list', sa.String(length=1120), nullable=True),
    sa.ForeignKeyConstraint(['attribute'], ['attribute.id'], ),
    sa.ForeignKeyConstraint(['site'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role')
    op.drop_table('beast')
    op.drop_table('user')
    op.drop_table('site')
    op.drop_table('banner')
    op.drop_table('attribute')
    # ### end Alembic commands ###
